# Dependencies
markdown:         kramdown
highlighter:      pygments

# Permalinks
permalink:        /:title.html
relative_permalinks: true

# Setup
title:            misshu
tagline:          "欲戴其冠，必承其重"
description:      "欲戴其冠，必承其重"
url:              "http://www.wuhuting.com"

author:
  name:           misshu

paginate:         8
